version: '3.8'

services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./chroma:/app/chroma
    environment:
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://ollama:11434
      - CHROMA_PATH=chroma
      - DATA_PATH=data
      - EMBEDDING_MODEL=nomic-embed-text
      - LLM_MODEL=phi3:mini
    depends_on:
      - ollama
    networks:
      - rag-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    networks:
      - rag-network

volumes:
  ollama_data:

networks:
  rag-network:
    driver: bridge 